### ISSUE TITLE
toml parsing error mod_mam module

### ISSUE THREAD

**Issue by macntech** [esl/MongooseIM#3735]
MongooseIM version: 5.1.0
Installed from: pkg

I get a toml parsing error during startup with the following configuration. 

```toml
[modules.mod_mam]
  pm.same_mam_id_for_peers = true
  muc.host = "URL"
```
According to documentation this should enable pm and muc on the mam module and set the parameters accordingly. After `mongooseimctl live` I can observe the following parsing error:

```
text="TOML configuration error: Malformed node" 
toml_value="#{
     <<\"muc\">> => #{<<\"host\">> => <<\"URL\">>},
     <<\"pm\">> => #{<<\"same_mam_id_for_peers\">> => true}
}" 
toml_path=modules.mod_mam key=muc 
Could not read the TOML configuration file
```

Please advise.
