### ISSUE TITLE
Error creating token sequence number while on token based connection

### ISSUE THREAD

**Issue by alvinlal** [esl/MongooseIM#4291]
MongooseIM version: 6.2.0
Installed from: pkg
Erlang/OTP version: 26

getting the following error on log while trying to get access token and refresh token on token based reconnection as specified [here](https://esl.github.io/MongooseDocs/latest/open-extensions/token-reconnection/)

this is the stanza that i am sending after successfull connection 👇 

```xml
<iq type='get' to='<jid of user>' id='123'>
    <query xmlns='erlang-solutions.com:xmpp:token-auth:0'/>
</iq>
```

this is what i am getting back 👇 
```xml
<iq from='<from jid>' to='<to jid>' id='123' type='error' xmlns='jabber:client'><error code='500' type='wait'><internal-server-error xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
```

this is the error being logged on the mongooseim logs 👇 
```
when=2024-05-31T10:11:15.141615+00:00 level=error what=auth_token_revocation_check_failed reason={badmatch,[]} pid=<0.2209.0> at=mod_auth_token:token/3:331 user=<username here>
stacktrace="mod_auth_token:get_key_for_host_type/2:397 mod_auth_token:hmac_opts/2:150 mod_auth_token:token_with_mac/2:144 
mod_auth_token:token/3:328 mod_auth_token:create_token_response/3:296 mod_auth_token:process_local_iq/4:284 mod_auth_token:process_iq/5:278 
mongoose_iq_handler:execute_handler/5:105" text="Error creating token sequence number"
 token_type=refresh server=<server name here> expiry_datetime={{2024,6,25},{10,11,15}} 
```

relevant config of `mod_auth_token` and `mod_keystore` 👇 

```toml
[modules.mod_auth_token]
  backend = "rdbms"
  validity_period.access = {value = 12, unit = "hours"}
  validity_period.refresh = {value = 25, unit = "days"}

[modules.mod_keystore]
  keys = [{name = "access_secret", type = "ram"}]
```

full config 👇 

```toml
[general]
  loglevel = "all"
  hosts = ["hostname here","localhost"]
  host_types = []
  default_server_domain = "localhost"
  registration_timeout = "infinity"
  language = "en"
  max_fsm_queue = 1000

[[listen.http]]
  port = 5280
  transport.num_acceptors = 10
  transport.max_connections = 1024

  [[listen.http.handlers.mod_bosh]]
    host = "_"
    path = "/http-bind"

  [[listen.http.handlers.mod_websockets]]
    host = "_"
    path = "/ws-xmpp"
    #timeout = 40_000
    #ping_rate = 30_000
    c2s_state_timeout = "infinity"

[[listen.http]]
  port = 5285
  transport.num_acceptors = 10
  transport.max_connections = 1024


  [[listen.http.handlers.mod_bosh]]
    host = "_"
    path = "/http-bind"

  [[listen.http.handlers.mod_websockets]]
    host = "_"
    path = "/ws-xmpp"
    #ping_rate = 30_000
    c2s_state_timeout = "infinity"

[[listen.http]]
  ip_address = "0.0.0.0"
  port = 8088
  transport.num_acceptors = 10
  transport.max_connections = 1024

  [[listen.http.handlers.mongoose_admin_api]]
    host = "_"
    path = "/api"
    username = "admin"
    password = "secret"

[[listen.http]]
  port = 8089
  transport.num_acceptors = 10
  transport.max_connections = 1024
  protocol.compress = true
  tls.verify_mode = "none"
  tls.certfile = "priv/ssl/fake_cert.pem"
  tls.keyfile = "priv/ssl/fake_key.pem"
  tls.password = ""

  [[listen.http.handlers.mongoose_client_api]]
    host = "_"
    path = "/api"

[[listen.http]]
  ip_address = "127.0.0.1"
  port = 5551
  transport.num_acceptors = 10
  transport.max_connections = 1024

  [[listen.http.handlers.mongoose_graphql_handler]]
    host = "localhost"
    path = "/api/graphql"
    schema_endpoint = "admin"
    username = "admin"
    password = "secret"

[[listen.http]]
  ip_address = "0.0.0.0"
  port = 5541
  transport.num_acceptors = 10
  transport.max_connections = 1024

  [[listen.http.handlers.mongoose_graphql_handler]]
    host = "_"
    path = "/api/graphql"
    schema_endpoint = "domain_admin"

[[listen.http]]
  ip_address = "0.0.0.0"
  port = 5561
  transport.num_acceptors = 10
  transport.max_connections = 1024

  [[listen.http.handlers.mongoose_graphql_handler]]
    host = "_"
    path = "/api/graphql"
    schema_endpoint = "user"

[[listen.c2s]]
  port = 5222
  access = "c2s"
  shaper = "c2s_shaper"
  max_stanza_size = 65536
  tls.verify_mode = "none"
  tls.certfile = "priv/ssl/fake_server.pem"

[[listen.s2s]]
  port = 5269
  shaper = "s2s_shaper"
  max_stanza_size = 131072

[[listen.service]]
  port = 8888
  access = "all"
  shaper_rule = "fast"
  ip_address = "127.0.0.1"
  password = "password here"

[auth]
  methods = ["rdbms"]

  [auth.rdbms]


[outgoing_pools.rdbms.default]
  scope = "global"
  workers = 5

  [outgoing_pools.rdbms.default.connection]
    driver = "mysql"
    host = "localhost"
    database = "mongooseim"
    username = "db username"
    password = "db password here"

#[services.service_admin_extra]

#[services.service_mongoose_system_metrics]

[modules.mod_ping]
  send_pings = true
  ping_interval = 10
  ping_req_timeout = 5
  timeout_action = "kill"

[modules.mod_offline]
  access_max_user_messages = "max_user_offline_messages"
  backend = "mnesia"

[modules.mod_offline_stub]

[modules.mod_pubsub]
  plugins = ["push"] # mandatory minimal config

[modules.mod_event_pusher.push]
  backend = "rdbms" # optional
  wpool.workers = 200 # optional
  plugin_module = "mod_event_pusher_push_plugin_enhanced" # optional
  virtual_pubsub_hosts = ["pubsub.@HOST@"]

[[modules.mod_event_pusher.http.handlers]]
  pool_name = "http_pool"

[outgoing_pools.http.http_pool]
     scope = "global"
     workers = 50

     [outgoing_pools.http.http_pool.connection]
        host = "http://localhost:8443"
        path_prefix = "/push/"
        request_timeout = 2000

[modules.mod_auth_token]
  backend = "rdbms"
  validity_period.access = {value = 12, unit = "hours"}
  validity_period.refresh = {value = 25, unit = "days"}

[modules.mod_keystore]
  keys = [{name = "access_secret", type = "ram"}]


[modules.mod_adhoc]


[modules.mod_disco]
  extra_domains = ["extra domain here"]
  users_can_see_hidden_services = false

[modules.mod_stream_management]
  ack_freq = 1
  buffer_max = 100
  resume_timeout = 10

[modules.mod_roster]

[modules.mod_register]
  ip_access = [
    {address = "127.0.0.0/8", policy = "allow"},
    {address = "0.0.0.0/0", policy = "deny"}
  ]
  access = "register"

[modules.mod_presence]

[modules.mod_sic]

[modules.mod_vcard]
  host = "vjud.@HOST@"

[modules.mod_bosh]

[modules.mod_carboncopy]

[shaper.normal]
  max_rate = 1000

[shaper.fast]
  max_rate = 50_000

[shaper.mam_shaper]
  max_rate = 1

[shaper.mam_global_shaper]
  max_rate = 1000

[acl]
  local = [{}]

[access]
  max_user_sessions = [
    {acl = "all", value = 10}
  ]

  max_user_offline_messages = [
    {acl = "admin", value = 5000},
    {acl = "all", value = 100}
  ]

  local = [
    {acl = "local", value = "allow"}
  ]

  c2s = [
    {acl = "blocked", value = "deny"},
    {acl = "all", value = "allow"}
  ]

  c2s_shaper = [
    {acl = "admin", value = "none"},
    {acl = "all", value = "normal"}
  ]

  s2s_shaper = [
    {acl = "all", value = "fast"}
  ]

  muc_admin = [
    {acl = "admin", value = "allow"}
  ]

  muc_create = [
    {acl = "local", value = "allow"}
  ]

  muc = [
    {acl = "all", value = "allow"}
  ]

  register = [
    {acl = "all", value = "allow"}
  ]

  mam_set_prefs = [
    {acl = "all", value = "default"}
  ]

  mam_get_prefs = [
    {acl = "all", value = "default"}
  ]

  mam_lookup_messages = [
    {acl = "all", value = "default"}
  ]

  mam_set_prefs_shaper = [
    {acl = "all", value = "mam_shaper"}
  ]

  mam_get_prefs_shaper = [
    {acl = "all", value = "mam_shaper"}
  ]

  mam_lookup_messages_shaper = [
    {acl = "all", value = "mam_shaper"}
  ]

  mam_set_prefs_global_shaper = [
    {acl = "all", value = "mam_global_shaper"}
  ]

  mam_get_prefs_global_shaper = [
    {acl = "all", value = "mam_global_shaper"}
  ]

  mam_lookup_messages_global_shaper = [
    {acl = "all", value = "mam_global_shaper"}
  ]

[s2s]
  use_starttls = "optional"
  certfile = "priv/ssl/fake_server.pem"
  default_policy = "deny"
  outgoing.port = 5269

#[[host_config]]
#  host = "anonymous.localhost"
#
#  [host_config.auth.anonymous]
#    allow_multiple_connections = true
#    protocol = "both"
```

**Comment by JanuszJakubiec** [comment]
Hi, to resolve the issue, update the mod_keystore configuration as follows:

```toml
[modules.mod_keystore]
  keys = [{name = "token_secret", type = "ram"}]
```
## Explanation
The mod_auth_token module uses two key names:

* **token_secret**: This key is used for both access and refresh tokens.
* **provision_pre_shared**: This key is used for provision tokens.

Currently, the documentation does not specify these details. We will update the documentation in the future to include this information.
