### ISSUE TITLE
System metrics always reporting zeros (Prometheus)

### ISSUE THREAD

**Issue by oybek** [esl/MongooseIM#4381]
MongooseIM version: latest master
Installed from: source
Erlang/OTP version: 26

System metrics like
`cets_info_available_nodes`
`system_memory_total`
`system_info_process_count`

always reporting zeros as values

**Comment by arcusfelis** [comment]
Hi,

There is a typo in the documentation.
```toml
[instrumentation]
  probe_interval = 60000
```

It should be in seconds
```toml
[instrumentation]
  probe_interval = 60
```

But default value = 15 sounds pretty good.

@JanuszJakubiec would update the docs.
